### ISSUE TITLE
jupyterlite does not start properly

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/p5-kernel#8]
## Description
When follwowing #1
![p5_error](https://user-images.githubusercontent.com/904752/135607416-1cdd6b87-e718-4bc9-8526-bd3cf7680c20.png)

## Reproduce

I followed #7  to get a sucessfull build
When I serve the page I see a blank page and the console-errors as in the screeenshot above

## Expected behavior
start jupyterlite

## Context

- JupyterLite version: 
- Operating System and version: ubuntu
- Browser and version: chrome

<details><summary>Browser Output</summary>
<pre>
Failed to load resource: the server responded with a status of 404 (Not Found)
:8000/jupyter-lite.ipynb:1 Failed to load resource: the server responded with a status of 404 (Not Found)
config-utils.js:200 failed get jupyter-config-data from http://127.0.0.1:8000/lab/jupyter-lite.ipynb
getLiteConfig @ config-utils.js:200
config-utils.js:200 failed get jupyter-config-data from http://127.0.0.1:8000/jupyter-lite.ipynb
getLiteConfig @ config-utils.js:200
consumes:40 Unsatisfied version 5.1.12 of shared singleton module @jupyterlab/coreutils (required ^5.1.13)
getSingletonVersion @ consumes:40
index.js:38 Failed to create module: package: @jupyterlite/p5-kernel-extension; module: ./extension
c @ index.js:38
index.js:469 Error: Shared module @jupyterlite/kernel doesn't exist in shared scope default
    at ensureExistence (consumes:19)
    at consumes:93
    at consumes:78
    at Object.webpack/sharing/consume/default/@jupyterlite/kernel (consumes:123)
    at consumes:159
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.consumes (consumes:142)
    at ensure chunk:6
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (ensure chunk:5)
(anonymous) @ index.js:469
p5js.png:1 Uncaught (in promise) ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (p5js.png:1)
    at i.registerPluginModule (app.js:61)
    at app.js:85
    at Array.forEach (<anonymous>)
    at i.registerPluginModules (app.js:84)
    at index.js:480
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @DerThorsten.

We also need https://github.com/jupyterlite/jupyterlite/pull/352 to be merged upstream and released, so it correctly exposes the shared packages (expected very soon).

**Comment by jtpio** [comment]
> We also need [jupyterlite/jupyterlite#352](https://github.com/jupyterlite/jupyterlite/pull/352) to be merged upstream and released

This should now be released in `0.1.0a11` and `0.1.0a12`

**Comment by jtpio** [comment]
Closing as this should now be fixed in the latest `jupyterlite`.
